### ISSUE TITLE
 weight

### ISSUE THREAD

**Issue by lclszsdnr** [Mr-Bigworth/MMCA#1]
Hi,May I ask if you can provide the training weights? Thank you very much

**Comment by Mr-Bigworth** [comment]
Thank you for your attention. You can refer to the following link for pretrained weights. [Link](https://drive.google.com/drive/folders/17CVnc5XOyqqDlg1veXRE9hY9r123Nvqx)
As we are currently busy with other tasks, we will consider the weights that can be used for inference in the future open source. And I highly recommend that you train it yourself, as its training cost is almost identical to that of TransVG.

**Comment by lclszsdnr** [comment]
Thank you very much for your reply. I noticed that the weight file in the link is the training result of transvg. Does it mean that all parameters should be initialized with this weight, or only the weights of the detr part should be used, because I saw that only the weight initialization of detr was declared in the train.sh file.

**Comment by Mr-Bigworth** [comment]
> Thank you very much for your reply. I noticed that the weight file in the link is the training result of transvg. Does it mean that all parameters should be initialized with this weight, or only the weights of the detr part should be used, because I saw that only the weight initialization of detr was declared in the train.sh file.

I'm sorry for any confusion caused. I quoted the wrong link in my reply. In fact, we use the same model initialization strategy as TransVG (the detr part is initialized with the pretrained weight).  And the link of the pretrained weight is as follows: [pretrained weight](https://drive.google.com/drive/folders/1SOHPCCR6yElQmVp96LGJhfTP46RxVwzF). We also shown it in the [GETTING_STARGTED.md](docs/GETTING_STARTED.md).

**Comment by lclszsdnr** [comment]
谢谢您的回复.但是我训练了一下结果不好，请问能加一下微信或者qq询问一下吗。我用的命令为   python -m torch.distributed.launch --nproc_per_node=4 --use_env train.py --batch_size 8 --lr_bert 0.00001 --aug_scale --aug_translate --aug_crop --backbone resnet101 --detr_model ./checkpoints/checkpoints/detr-r101-gref.pth --bert_enc_num 12 --detr_enc_num 6 --dataset gref_umd --max_query_len 40 --output_dir /root/autodl-tmp/mmca/outputs/refcocog_gsplit_r101" . 因为在训练时报错， 我修改了transvg.py 中self.text_proj = nn.Linear(self.textmodel.num_channels, hidden_dim)” 为self.text_proj = nn.Linear(768, hidden_dim). 这应该不是训练错误的原因对吗？十分感谢您的帮助，我的qq为354793567.

**Comment by Mr-Bigworth** [comment]
> 谢谢您的回复.但是我训练了一下结果不好，请问能加一下微信或者qq询问一下吗。我用的命令为 python -m torch.distributed.launch --nproc_per_node=4 --use_env train.py --batch_size 8 --lr_bert 0.00001 --aug_scale --aug_translate --aug_crop --backbone resnet101 --detr_model ./checkpoints/checkpoints/detr-r101-gref.pth --bert_enc_num 12 --detr_enc_num 6 --dataset gref_umd --max_query_len 40 --output_dir /root/autodl-tmp/mmca/outputs/refcocog_gsplit_r101" . 因为在训练时报错， 我修改了transvg.py 中self.text_proj = nn.Linear(self.textmodel.num_channels, hidden_dim)” 为self.text_proj = nn.Linear(768, hidden_dim). 这应该不是训练错误的原因对吗？十分感谢您的帮助，我的qq为354793567.

结果不好是大致多少哇，有在三个数据集上都试一下么

**Comment by Mr-Bigworth** [comment]
> 谢谢您的回复.但是我训练了一下结果不好，请问能加一下微信或者qq询问一下吗。我用的命令为 python -m torch.distributed.launch --nproc_per_node=4 --use_env train.py --batch_size 8 --lr_bert 0.00001 --aug_scale --aug_translate --aug_crop --backbone resnet101 --detr_model ./checkpoints/checkpoints/detr-r101-gref.pth --bert_enc_num 12 --detr_enc_num 6 --dataset gref_umd --max_query_len 40 --output_dir /root/autodl-tmp/mmca/outputs/refcocog_gsplit_r101" . 因为在训练时报错， 我修改了transvg.py 中self.text_proj = nn.Linear(self.textmodel.num_channels, hidden_dim)” 为self.text_proj = nn.Linear(768, hidden_dim). 这应该不是训练错误的原因对吗？十分感谢您的帮助，我的qq为354793567.

你的那个修改按理应该不会报错，因为self.textmodel.num_channels实际上加载的是bert的channels，它应该就是768。修改了也没有关系，但是我不太确定你为啥会报这个错，因此会担心是否读取了正确的bert model。

**Comment by Mr-Bigworth** [comment]
> 谢谢您的回复.但是我训练了一下结果不好，请问能加一下微信或者qq询问一下吗。我用的命令为 python -m torch.distributed.launch --nproc_per_node=4 --use_env train.py --batch_size 8 --lr_bert 0.00001 --aug_scale --aug_translate --aug_crop --backbone resnet101 --detr_model ./checkpoints/checkpoints/detr-r101-gref.pth --bert_enc_num 12 --detr_enc_num 6 --dataset gref_umd --max_query_len 40 --output_dir /root/autodl-tmp/mmca/outputs/refcocog_gsplit_r101" . 因为在训练时报错， 我修改了transvg.py 中self.text_proj = nn.Linear(self.textmodel.num_channels, hidden_dim)” 为self.text_proj = nn.Linear(768, hidden_dim). 这应该不是训练错误的原因对吗？十分感谢您的帮助，我的qq为354793567.

还有一个办法是你可以先跑一遍transvg，如果transvg能正常复现，只需要把我的[models_mmca_vector_based](https://github.com/Mr-Bigworth/MMCA/tree/main/models_mmca_vector_based)目录覆盖掉transvg的model目录，然后跑一下看看结果。建议'--clip_max_norm', default=0.1'保证训练稳定

**Comment by Mr-Bigworth** [comment]
> 谢谢您的回复.但是我训练了一下结果不好，请问能加一下微信或者qq询问一下吗。我用的命令为 python -m torch.distributed.launch --nproc_per_node=4 --use_env train.py --batch_size 8 --lr_bert 0.00001 --aug_scale --aug_translate --aug_crop --backbone resnet101 --detr_model ./checkpoints/checkpoints/detr-r101-gref.pth --bert_enc_num 12 --detr_enc_num 6 --dataset gref_umd --max_query_len 40 --output_dir /root/autodl-tmp/mmca/outputs/refcocog_gsplit_r101" . 因为在训练时报错， 我修改了transvg.py 中self.text_proj = nn.Linear(self.textmodel.num_channels, hidden_dim)” 为self.text_proj = nn.Linear(768, hidden_dim). 这应该不是训练错误的原因对吗？十分感谢您的帮助，我的qq为354793567.

或者先跑一下r50的结果试一下也可以

**Comment by lclszsdnr** [comment]
好的，十分感谢回复，我再试一下，可能哪里有点小问题
